name: Git Version
on: push

jobs:
  branch_version:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: 'v'
          skip-commit: 'true'
          skip-version-file: 'true'
          config-file-path: './changelog-config.js'
        
      - name: see version
        run: echo "${{ steps.nextversion.outputs.nextVersion }}"